# Generated by Django 4.2.13 on 2024-07-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Summer_APP', '0002_live_wallpaper1_delete_live_wallpaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Live_Wallpaper1',
        ),
    ]
